version: "3.9"

services:
  persistence:
    image: mastermind-persistence-service
    build:
      context: ./Persistence/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    container_name: persistence_service
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
    tty: true
    working_dir: /fileio
    volumes:
      - ./:/fileio:xro
    depends_on:
      - database

  mongoDB:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mastermind-mongo
    environment:
      MONGO_INITDB_HOST: mastermind-mongo
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mastermind

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    container_name: mastermind-database
    environment:
      MYSQL_HOST: mastermind-database
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mastermind
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
     - .:/var/lib/sql/mastermind

  core:
    image: mastermind-core-service
    build:
      context: ./Core/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    container_name: core_service
    depends_on:
      - persistence
    environment:
      CORE_SERVICE_HOST: core
      CORE_SERVICE_PORT: 8080
    tty: true

  ui:
    network_mode: "host"
    image: mastermind-ui-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: ui_service
    depends_on:
      - core
      - persistence
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
      CORE_SERVICE_HOST: core
      CORE_SERVICE_PORT: 8080